settings:
  variables:
    entity_tablet: switch.galaxy_tab_a_screensaver
    entity_browser_mod: media_player.browser_dd239c79_406b9d77
    translate_unknown: Unknown
    translate_idle: Inactive
    translate_home: Yes
    translate_not_home: No
    translate_available: available
    translate_no_updates: No updates
    translate_update_available: update available
    translate_updates_available: updates available
