- id: '1662537236129'
  alias: Front door unlocked notification
  description: Sends phone notification if the front door is unlocked for too long
  trigger:
  - platform: state
    entity_id:
    - lock.front_door
    to: unlocked
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - device_id: 49610d025fb7bbde0d30096f85a95d2f
    domain: mobile_app
    type: notify
    message: Front door is unlocked!
  - device_id: da2a54d25f82a71b18bd36465060d5f3
    domain: mobile_app
    type: notify
    message: Front door is unlocked!
  mode: single
- id: '1662546484568'
  alias: Start vacuum when no one is home
  description: Starts vacuum if both Edward and Linda are not home and only if vacuum
    has not been run today already
  trigger:
  - platform: state
    entity_id:
    - device_tracker.edwards_pixel
    to: not_home
  - platform: state
    entity_id:
    - device_tracker.lindas_iphone
    to: not_home
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: "{% set last = state_attr('automation.vacuum',\n           \
        \              'last_triggered') %}\n{{ last is none or\n   as_timestamp(last)|timestamp_custom('%j')|int\
        \ !=\n   now().strftime('%j')|int }}\n"
    - condition: state
      entity_id: device_tracker.edwards_pixel
      state: not_home
    - condition: state
      entity_id: device_tracker.lindas_iphone
      state: not_home
  action:
  - service: vacuum.start
    data: {}
    target:
      entity_id: vacuum.vacuum
  - device_id: 49610d025fb7bbde0d30096f85a95d2f
    domain: mobile_app
    type: notify
    message: Vacuum started
    title: Vacuum started
  mode: single
- id: '1663596447311'
  alias: Clean robot dock reminder daily
  description: If either Edward or Linda is home and the dock has not been cleaned
    for more than 3 days then send a reminder to clean dock
  trigger:
  - platform: time
    at: '20:30:00'
  condition:
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: counter.clean_vacuum_dock_counter
      above: 3
    - condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.edwards_pixel
        state: home
      - condition: state
        entity_id: device_tracker.lindas_iphone
        state: home
  action:
  - device_id: 49610d025fb7bbde0d30096f85a95d2f
    domain: mobile_app
    type: notify
    message: Time to clean the vacuum dock
    title: Scan the NFC tag after it is cleaned
  - device_id: da2a54d25f82a71b18bd36465060d5f3
    domain: mobile_app
    type: notify
    message: Time to clean the vacuum dock
    title: Scan the NFC tag after it is cleaned
  - service: tts.cloud_say
    data:
      entity_id: all
      message: Clean the vacuum!
  mode: single
- id: '1664443046441'
  alias: Vacuum dock tag scanned
  description: Resets vacuum counter when tag is scanned
  trigger:
  - platform: tag
    tag_id: 3016833c-7067-47f5-8551-c1498159b3fe
  condition: []
  action:
  - service: counter.reset
    data: {}
    target:
      entity_id: counter.clean_vacuum_dock_counter
  mode: single
- id: '1664443190969'
  alias: Water heater reminder daily
  description: ''
  trigger:
  - platform: time
    at: '21:30:00'
  condition: []
  action:
  - service: tts.cloud_say
    data:
      entity_id: all
      message: Turn on the water heater
  - device_id: 49610d025fb7bbde0d30096f85a95d2f
    domain: mobile_app
    type: notify
    message: Turn on the water heater
    title: Turn on the water heater
  mode: single
- id: '1664443565606'
  alias: Vitamin Tracker
  description: ''
  trigger:
  - platform: tag
    tag_id: af9c3c26-3f73-45cc-b08d-22862960c7ba
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.vitamin_tracker
        state: 'off'
      sequence:
      - service: tts.cloud_say
        data:
          entity_id: media_player.office_speaker
          message: Yes, take your vitamin
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.vitamin_tracker
    default:
    - service: tts.cloud_say
      data:
        entity_id: media_player.office_speaker
        message: STOP! You have already had your vitamins for the day.
  mode: single
- id: '1664443685941'
  alias: Vitamin reminder daily
  description: ''
  trigger:
  - platform: time
    at: 03:00:00
  condition:
  - condition: state
    entity_id: input_boolean.vitamin_tracker
    state: 'off'
  - condition: state
    entity_id: device_tracker.edwards_pixel
    state: home
  action:
  - service: tts.cloud_say
    data:
      entity_id: all
      message: Take your vitamins
  mode: single
- id: '1664443767385'
  alias: Daily stuff
  description: ''
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.vitamin_tracker
  - service: counter.increment
    data: {}
    target:
      entity_id: counter.clean_vacuum_dock_counter
  mode: single
- id: '1664444686046'
  alias: Tag Night stand Edward is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 0b7294af-9601-4747-823b-a2f7cbcb1772
  condition: []
  action:
  - device_id: 52155b80fed6c9e296e5d2a8118c0499
    domain: climate
    entity_id: climate.dining_room_ac
    type: set_hvac_mode
    hvac_mode: 'off'
  - device_id: 9830e6e77967529a266e9f3e8171c05e
    domain: climate
    entity_id: climate.living_room_ac
    type: set_hvac_mode
    hvac_mode: 'off'
  - type: turn_off
    device_id: f0ee0cff2aaadfbdba0a2b9f0de1ae48
    entity_id: remote.sony_kd_49x9000f
    domain: remote
  - service: remote.send_command
    data:
      device: office_ac
      command: 'off'
    target:
      entity_id: remote.office_remote
  mode: single
- id: '1664444826301'
  alias: Tag Night stand Linda is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 40149d82-b7bb-4e47-9e5e-938e8cbc873f
  condition: []
  action:
  - device_id: 52155b80fed6c9e296e5d2a8118c0499
    domain: climate
    entity_id: climate.dining_room_ac
    type: set_hvac_mode
    hvac_mode: 'off'
  - device_id: 9830e6e77967529a266e9f3e8171c05e
    domain: climate
    entity_id: climate.living_room_ac
    type: set_hvac_mode
    hvac_mode: 'off'
  - type: turn_off
    device_id: f0ee0cff2aaadfbdba0a2b9f0de1ae48
    entity_id: remote.sony_kd_49x9000f
    domain: remote
  - service: remote.send_command
    data:
      device: office_ac
      command: 'off'
    target:
      entity_id: remote.office_remote
  mode: single
