button_card_templates: !include_dir_merge_named button_card_templates

views:
  - type: custom:grid-layout
    title: Home
    layout:
      #default
      margin: 0
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .           .       .       ."
        "sidebar  dining_room living_room  office ."
        "sidebar  bedroom       .       .       ."
        "sidebar  footer      footer  footer  ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.7)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .           .        ."
            ".  sidebar     sidebar  ."
            ".  dining_room  living_room   ."
            ".  office       bedroom      ."
            ".  footer      footer   ."
            ".  .           .        ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .           .       ."
            "sidebar  dining_room  living_room  ."
            "sidebar  office      bedroom    ."
            "sidebar  footer      footer  ."
            "sidebar  .           .       ."
    cards:
      #extra_styles fix, do not remove
      #also warn if theme is not set

      - type: custom:button-card
        view_layout:
          grid-area: 1 / 2 / 2 / 5
        name: SET THEME TO "tablet" IN PROFILE
        tap_action:
          action: navigate
          navigation_path: /profile
        styles:
          card:
            - display: >
                [[[
                  return hass.themes.theme === 'tablet'
                      ? 'none'
                      : 'initial';
                ]]]
          name:
            - z-index: 1
            - overflow: visible
            - color: red
            - font-weight: bolder
            - font-size: xxx-large
            - background: yellow

      #################################################
      #                                               #
      #                    SIDEBAR                    #
      #                                               #
      #################################################

      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:
          - type: custom:button-card
            entity: sensor.template_sidebar
            template: sidebar

      #################################################
      #                                               #
      #                  LIVING ROOM                  #
      #                                               #
      #################################################

      - type: grid
        title: Living Room
        view_layout:
          grid-area: living_room
        columns: 2
        cards:
          - type: custom:button-card
            entity: climate.living_room_ac
            name: AC
            double_tap_action: !include popup/living_room_ac.yaml
            template:
              - base
              - icon_climate
              - circle
            variables:
              circle_input: >
                [[[
                  if (entity) {
                      return entity.state === 'cool'
                          ? Math.round(entity.attributes.temperature).toString()
                          : Math.round(entity.attributes.current_temperature).toString();
                  }
                ]]]
              circle_input_unit: "°C"

          - type: custom:button-card
            entity: media_player.shield
            name: Tv
            state_display: >
              [[[
                if (variables.state === 'playing') {
                    return 'On';
                }
                if (variables.state === true) {
                    return variables.translate_unknown;
                }
              ]]]
            double_tap_action: !include popup/living_room_tv.yaml
            template:
              - base
              - icon_tv
              - loader

      #################################################
      #                                               #
      #                  DINING ROOM                  #
      #                                               #
      #################################################

      - type: grid
        title: Dining Room
        view_layout:
          grid-area: dining_room
        columns: 2
        cards:
          - type: custom:button-card
            entity: vacuum.vacuum
            name: Vacuum
            tap_action:
              action: call-service
              service: script.toggle_vacuum
            template:
              - base
              - icon_vacuum
              - loader

          - type: custom:button-card
            entity: climate.dining_room_ac
            name: AC
            double_tap_action: !include popup/dining_room_ac.yaml
            template:
              - base
              - icon_climate
              - circle
            variables:
              circle_input: >
                [[[
                  if (entity) {
                      return entity.state === 'cool'
                          ? Math.round(entity.attributes.temperature).toString()
                          : Math.round(entity.attributes.current_temperature).toString();
                  }
                ]]]
              circle_input_unit: "°C"

          - type: custom:button-card
            entity: lock.front_door
            name: Front Door
            double_tap_action: !include popup/front_door.yaml
            template:
              - base
              - icon_closet
              - loader

      ### Office
      - type: grid
        title: Office
        view_layout:
          grid-area: office
        columns: 2
        cards:
          - type: custom:button-card
            name: AC
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                device: office_ac
                command: "power"
                entity_id: remote.office_remote
            template:
              - base
              - icon_climate

      #################################################
      #                                               #
      #                    Bedroom                    #
      #                                               #
      #################################################

      - type: grid
        title: Bedroom
        view_layout:
          grid-area: bedroom
        columns: 2
        cards:
          - type: custom:button-card
            entity: cover.bedroom_curtain
            name: Curtain
            tap_action: !include popup/bedroom_curtain.yaml
            double_tap_action: !include popup/bedroom_curtain.yaml
            template:
              - base
              - icon_curtain
              - loader

      #################################################
      #                                               #
      #                    FOOTER                     #
      #                                               #
      #################################################

      - type: horizontal-stack
        view_layout:
          grid-area: footer
        cards:
          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:nas"></ha-icon> NAS
            tap_action: !include popup/footer_nas.yaml
            triggers_update:
              - binary_sensor.nas_update_available
              - sensor.nas_volume_1_status
              - binary_sensor.nas_security_status
              - sensor.disk_use_percent
            variables:
              notify: >
                [[[
                  let id = this._config.triggers_update;
                  if (id.every(e => states[e]))
                      return states[id[0]].state === 'on'
                          ? 1
                          : states[id[1]].state === 'background_scrubbing' ||
                            states[id[2]].state === 'on' ||
                            parseFloat(states[id[3]].state) >= 85;
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:arrow-up-bold-circle-outline"></ha-icon> Updates
            tap_action: !include popup/footer_updates.yaml
            triggers_update:
              - sensor.hacs
              - sensor.docker_hub_beta
              - sensor.docker_hub
            variables:
              notify: >
                [[[
                  let id = this._config.triggers_update;
                  if (id.every(e => states[e])) {
                      let hacs = parseInt(states[id[0]].state),
                          installed = hass.config.version,
                          latest = installed.includes('b')
                              ? states[id[1]].state
                              : states[id[2]].state;

                      if (latest.includes('.') && Number.isInteger(hacs))
                          return hacs + (installed !== latest ? 1 : 0);
                  }
                  return 0;
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:robot-vacuum-variant"></ha-icon> Vacuum
            tap_action: !include popup/footer_vacuum.yaml
            triggers_update:
              - sensor.date
            variables:
              notify: >
                [[[
                  let id = states['sensor.morty_last_clean_end'];
                  if (id) return (Date.now() - Date.parse(id.state)) > 6048e5;
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:router-wireless"></ha-icon> Router
            tap_action: !include popup/footer_router.yaml
            triggers_update:
              - binary_sensor.template_udm_internet
            variables:
              notify: >
                [[[
                  let id = this._config.triggers_update;
                  if (id.every(e => states[e]))
                      return states[id[0]].state === 'on'
                          ? 1
                          : states[id[1]].state === 'off';
                ]]]
            template: footer
